development:
  database: message_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: root

test:
  database: message_test
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: root
  password: root

production:
  database: message_production
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: message
  password: message
